[package]
name = "petri-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "The petri command line."
publish = false

[lints]
workspace = true

[[bin]]
name = "petri"
path = "src/main.rs"

[dependencies]
petri = { workspace = true }
cli = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
testkit = { workspace = true }
serde_json = { workspace = true }
