[package]
name = "petri-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The petri command line."

[lints]
workspace = true

[[bin]]
name = "petri"
path = "src/main.rs"

[dependencies]
petri = { workspace = true }
cli = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
