[package]
name = "petri"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The petri CLI."

[[bin]]
name = "petri"
path = "src/main.rs"

[dependencies]
ir = { workspace = true }
frontend = { workspace = true }
frontend-gha = { workspace = true }
frontend-native = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
